return {
  version = "1.1",
  luaversion = "5.1",
  orientation = "orthogonal",
  width = 200,
  height = 50,
  tilewidth = 32,
  tileheight = 32,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      name = "Object Layer 1",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "wall",
          type = "",
          shape = "polyline",
          x = 74,
          y = 145,
          width = 0,
          height = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 491, y = -3 },
            { x = 584, y = 48 }
          },
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "polyline",
          x = 800,
          y = 221,
          width = 0,
          height = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -219, y = 136 },
            { x = -472, y = 135 },
            { x = -565, y = 218 },
            { x = -697, y = 217 }
          },
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "polyline",
          x = 30,
          y = 401,
          width = 0,
          height = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 53, y = 0 }
          },
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "polyline",
          x = 89,
          y = 352,
          width = 0,
          height = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 51, y = -1 }
          },
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "polyline",
          x = 173,
          y = 313,
          width = 0,
          height = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 52, y = -1 }
          },
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "polyline",
          x = 273,
          y = 269,
          width = 0,
          height = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 66, y = -2 }
          },
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "polyline",
          x = 382,
          y = 232,
          width = 0,
          height = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 79, y = -1 }
          },
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "polyline",
          x = 480,
          y = 199,
          width = 0,
          height = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 77, y = 1 }
          },
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 588,
          width = 252,
          height = 171,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "rectangle",
          x = 419,
          y = 675,
          width = 451,
          height = 40,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "rectangle",
          x = 441,
          y = 496,
          width = 70,
          height = 79,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "rectangle",
          x = 668,
          y = 550,
          width = 90,
          height = 62,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "rectangle",
          x = 570,
          y = 580,
          width = 49,
          height = 35,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "rectangle",
          x = 59,
          y = 925,
          width = 517,
          height = 41,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 721,
          y = 958,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 750,
          y = 960,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 769,
          y = 963,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 735,
          y = 974,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 790,
          y = 974,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 773,
          y = 983,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 798,
          y = 993,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 780,
          y = 1001,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 755,
          y = 986,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 735,
          y = 993,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 714,
          y = 985,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 705,
          y = 974,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 700,
          y = 1002,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 689,
          y = 993,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 723,
          y = 1008,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 746,
          y = 1008,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 766,
          y = 1009,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 798,
          y = 1015,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 780,
          y = 1020,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 817,
          y = 1001,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 810,
          y = 979,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 833,
          y = 985,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 833,
          y = 1011,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 817,
          y = 1027,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 796,
          y = 1033,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 847,
          y = 999,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 678,
          y = 979,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 693,
          y = 954,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 659,
          y = 956,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 675,
          y = 963,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 652,
          y = 983,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 666,
          y = 997,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "ellipse",
          x = 677,
          y = 1009,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "polyline",
          x = 299,
          y = 1139,
          width = 0,
          height = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 14, y = 12 },
            { x = 28, y = 18 },
            { x = 48, y = 23 },
            { x = 80, y = 25 },
            { x = 98, y = 28 },
            { x = 109, y = 30 },
            { x = 137, y = 41 },
            { x = 151, y = 46 },
            { x = 174, y = 61 },
            { x = 178, y = 64 },
            { x = 189, y = 80 },
            { x = 196, y = 96 },
            { x = 201, y = 112 },
            { x = 215, y = 139 },
            { x = 230, y = 146 },
            { x = 249, y = 155 },
            { x = 272, y = 157 },
            { x = 299, y = 160 },
            { x = 320, y = 173 },
            { x = 354, y = 187 },
            { x = 377, y = 198 },
            { x = 399, y = 221 },
            { x = 417, y = 246 },
            { x = 436, y = 263 },
            { x = 468, y = 263 },
            { x = 495, y = 263 },
            { x = 504, y = 263 },
            { x = 523, y = 258 },
            { x = 548, y = 246 },
            { x = 579, y = 228 },
            { x = 627, y = 210 },
            { x = 671, y = 215 },
            { x = 732, y = 221 },
            { x = 782, y = 240 },
            { x = 808, y = 260 },
            { x = 851, y = 294 },
            { x = 862, y = 312 },
            { x = 863, y = 324 },
            { x = 883, y = 379 },
            { x = 888, y = 408 },
            { x = 894, y = 454 }
          },
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "polygon",
          x = 844,
          y = 1150,
          width = 0,
          height = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 169, y = -69 },
            { x = 294, y = -5 },
            { x = -135, y = 84 }
          },
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "polygon",
          x = 513,
          y = 1050,
          width = 0,
          height = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 109, y = -14 },
            { x = 174, y = -2 },
            { x = 226, y = 48 },
            { x = 164, y = 20 },
            { x = 109, y = 0 }
          },
          properties = {}
        },
        {
          name = "wall",
          type = "",
          shape = "polygon",
          x = 449,
          y = 1107,
          width = 0,
          height = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 118, y = 12 },
            { x = 119, y = 25 },
            { x = 189, y = 27 },
            { x = 207, y = 64 },
            { x = 164, y = 80 },
            { x = 189, y = 52 },
            { x = 164, y = 43 },
            { x = 96, y = 48 },
            { x = 98, y = 27 },
            { x = -9, y = 20 },
            { x = -180, y = -61 }
          },
          properties = {}
        },
        {
          name = "player",
          type = "",
          shape = "rectangle",
          x = 94,
          y = 55,
          width = 37,
          height = 35,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
